### ISSUE TITLE
Infinite loop is possible with Zmalloc()

### ISSUE THREAD

**Issue by Explorer09** [MrKrzYch00/zopfli#10]
(Hello. This is the first time I contribute to this.)

I'm not sure of the purpose of Zmalloc() function (introduced in commit 9314d067983de70d7e33e4d976138a7d2a686c4a), but it look like this code of Zmalloc() has two problems:

1. It is possible to go infinite loop. It did not provide a timeout mechanism (e.g. number of tries), and a call with ridiculously large size (`Zmalloc(SIZE_MAX)`) could hang the program.
2. The error message would be printed repeatedly, while I expect it prints once (a fatal error message, or a success with warning message about how many times it tried to allocate, if it didn't succeed the first try).

```
void *Zmalloc(size_t size) {
  void *ptr;
  if(size == 0) return NULL;
  for(;;) {
    ptr = malloc(size);
    if(ptr == NULL) {
      unsigned long x = (unsigned long)size;
      fprintf(stderr," ERROR: Couldn't allocate %lu bytes of memory!\n",x);
      sleep(60);
    } else {
      break;
    }
  }
  return ptr;
}
```

**Comment by MrKrzYch00** [comment]
That's exactly what it is supposed to do by design. If for example one is away from computer and something starts to "eat" too much of memory or there are blocks heavy on memory being compressed (in case of multithreading) it will still wait for memory to (maybe) become available. Of course it may so happen that you may have not enough memory installed to ever compress the file. Then you have still CTRL+C to use. Though the message could be clearer on how much memory it tried to allocate to easier verify if it will ever start compressing...

**Comment by Explorer09** [comment]
Beinging in a regression that could happen in many use cases just to solve one case is a bad idea, and that's why I consider this an issue.

There are many reasons why memory allocation could fail:
1. The memory block may be temporarily unavailable until another process frees it.
2. A local administrator policy caps the maximum memory allowed per user or per process.
3. The user's system simply has not much RAM, and for some reasons (hard disk limits or OS configuration mistakes) they cannot get more swap space either.
4. It's a Zrealloc() call, and the allocator isn't clever enough to enlarge memory block in place, and end up waiting for more memory then it needs.

It seems like Zmalloc only intends to address the first case. Even for that case, it had no measures for potential _deadlocks_. (And Ctrl+C might not be the solution here, since there's no guarantee that Zmalloc() would never be called after the first Ctrl+C is received.) I mean, it would better make the code more robust in other way, than trying to hack the malloc interface. And if we do want to make a wrapper on malloc, I suggest at least one change should be done:
* Make it listen to a (global) variable that determines whether Zmalloc should wait and retry or not, and number of retries we are allowed to do. (If user wants indefinite wait, he can set the number of retries to a large value such as 32767.)
* If Ctrl+C is received, the wait should be disabled so that the program can eventually stop (whether it's a successful or an abnormal stop). This can be implemented in the same variable.

**Comment by MrKrzYch00** [comment]
I understood your first post very well and as I wrote, it was done like that by design. And actually I see it already has an information on how much memory it tried to allocate, so ignore my last sentence in previous comment.

I was thinking about making it stop on 10th try but decided not to.

Did you maybe test the performance after implementing global variable on *alloc wrappers?

**Comment by MrKrzYch00** [comment]
Added compile-time directive. Not tested.

**Comment by MrKrzYch00** [comment]
Up to the user to compile it with malloc tries limiter, as controlling it with command line option requires that option to be passed to wrapper every time which I'm not sure is good for heavy heap manipulation. By default it's infinite loop.
