### ISSUE TITLE
ZopfliPNG v.16 Windows x86 non-working options

### ISSUE THREAD

**Issue by Adreitz** [MrKrzYch00/zopfli#4]
Hi, MrKrzYch00.

I'm seeing several problems with non-working CLI options in the v.16 build of ZopfliPNG that you posted to Encode.ru, related to the added pngwolf functionality. ZopfliPNG complains if I try to provide any of the following options:

--ga_stagnate_evaluations=X (I assume the other GA-related options don't work either)
--filters=0-4 (complains about the "-", which should be OK per the help text)
--filters=ywig (none of these advanced filters are accepted, either alone or in combination. m/e/b work.)
--zopfli-filters

I'd appreciate if you could fix these issues and upload a new release.

Thanks,
Aaron

PS Why is --cbs no longer supported in ZopfliPNG? I don't want to have to mess around with a bunch of little programs to turn a gz result back into a png. If you can't re-enable this option for technical reasons, please at least provide a switch like --use_current_splitting to directly reproduce the block splitting from the input file to the output, to be compatible with huffmix. Thanks.

**Comment by Adreitz** [comment]
Never mind, I made a mistake (ran an old version). If you can still look into re-implementing --cbs support, that would be great.

**Comment by MrKrzYch00** [comment]
Haha, yeah I was about to ask this. But thanks to this I found some part of code that shouldn't be in a place where --zopfli_filters was implemented. :)

About --cbs, there is a problem. When You apply filters and other stuff to PNG file (especially those providing some loss to image data) the input data (and size) MAY differ, so then provided split points are not guaranteed to be still the best.

About Your idea of switch, it couldn't be efficiently implemented for mentioned reasons. Zopfli on the other hand could somehow be able to parse compressed streams of PNG and/or GZ file and recompress blocks without altering block split points. However, Zopfli is only able to compress data, not parse already compressed streams as rezop does, because it doesn't have decompressor implemented.

I think some script frontend would be easier to implement here and maybe ability for ZopfliPNG to dump best split points to file similar to how --cbd works in Zopfli.

**Comment by Adreitz** [comment]
Thanks. Most of the time, I run zopflipng with --filters=p only. In this case, the input data won't differ at all from the original file, so --cbs should work fine. I understand that changing filters changes everything else. My typical workload involves first optimizing the filters with pngwolf, then hammering pngout/deflopt/huffmix with decrementing values of -n (starting from some "high-enough" -n depending on the input file and the time I am willing to spend) and many trials of -r (and sometimes trials of -s1, -s2, and -s3 as well). Once I get down to -n2, I then want to switch to zopflipng as a different compressor for the same block splits and huffmix the results. That way, I can get the best of both worlds (pngout vs zopfli). Occasionally zopflipng's block splits end up being better when used alone, but not often compared to the above sequence.

Aaron

**Comment by MrKrzYch00** [comment]
Hmm, after a bit of thinking things out it may be wiser to merge zip2gz, gz2zip, zip2zlib and zlib2png into one tool supporting all conversions as well as ability to decompress original IDAT from PNG file for Zopfli processing (and other deflate tools like kzip or 7-zip, because then we are not limited to PNG-only tools, any ZIP/GZ compressor could be then tested as long as the extacted IDAT belong to PNG we will be mixing the result with later)... Did You try --pass=99 to see if ZopfliPNG produced smaller size after recompressing stuff than pngout/kzip with -n -r variations?

**Comment by Adreitz** [comment]
Testing now using --all --pass=99 on a sample file that I compressed really well previously. I'll let you know the results.

**Comment by Adreitz** [comment]
Hmm. Well, the ZopfliPNG results were worse than my previous results by 65 bytes. But it looks like ZopfliPNG changed the palette, and I'm not sure what the results would have been if this hadn't happened.
![103_gplateaupath 860](https://cloud.githubusercontent.com/assets/11577741/14395246/96cbfa6a-fd9e-11e5-8a16-89b92fc34f98.png)
![103_gplateaupath 860 png_z](https://cloud.githubusercontent.com/assets/11577741/14395247/992328b0-fd9e-11e5-89b9-6c3ff76329d4.png)

I also didn't try really hard, having set --mui=1000 so the processing wouldn't take forever.

**Comment by MrKrzYch00** [comment]
Hmm, no idea, as ZopfliPNG is a bit alien to me, someone else was doing all the merged changes: https://github.com/MegaByte/zopfli/tree/truecryogenetic . I just merge it here to allow usage of those changes with my Zopfli improvements. When the palette code is optimized on that fork, it will land here.

**Comment by MrKrzYch00** [comment]
I uploaded ZIP/GZ/ZLIP/PNG converter named krzydefc.exe to zopfli krzymod 1st post. It can convert directly from mentioned formats to the others. So You can easly extract PNG IDAT to ZIP, GZ or ZLIB or put it back with --pngoriginalfilename.png switch.

**Comment by MrKrzYch00** [comment]
Last palette work was merged 9 days ago.

In the incoming month I will release all binaries as v16.1
