### ISSUE TITLE
Is it possible to merge back to upstream?

### ISSUE THREAD

**Issue by PeterDaveHello** [MrKrzYch00/zopfli#5]
Both the origin and your forked zopfli is awesome, I just wonder if it's possible to sned your work back to upstream? So that more and more users can benifit from it? Thanks a lot. 

cc @lvandeve

**Comment by MrKrzYch00** [comment]
I don't mind merging my changes to Zopfli, though there are things that may require some cleaning up  and/or completing (note that I'm programming in C since a bit more than a year lol, I'm self learner). One of those things is for example ZIP multi-file support: special file name characters are not properly parsed, not accepting empty directories and files. To, of course, not take all the credit by myself, some features were implemented basing on findings and/or code changes by Encode.ru (http://encode.ru/forums/2-Data-Compression) members.

As for ZopfliPNG I'm not sure if all changes comply to Google LA, as I mostly use someone else's work (https://github.com/MegaByte/zopfli), so I can't speak for these code changes.

There are few things I know of that may be candidates for further work to be done:
- CTRL+C handler is not working correctly with ZopfliPNG,
- containers are handled by BIN part and I'm not sure if LIB part ones are bug-free,
- LIB part is incompatible due to additional parameters (that can be NULL) required,
- CTRL+C (or other handler) should pause work, show some interactive menu by separate thread for on-fly option changes (this was a work I had in mind to do, but not having my vein at this moment to start :)
- pass switch should keep block split history to exit early when same block split points are selected during recompression work (it would be ideal to additionally re-use previous block results instead of iterating again if some split points were not altered),
- restore points are not useful in multi-file mode and are untested for files bigger than ZOPFLI_MASTER_BLOCK size,
- restore points should work on blocks instead of already appended LZ77 stream to support out-of-order work (best would be for them to support internal iteration progress variables so the compression could be resumed just the way it was before aborting work. My wild guess is that this way they would be much smaller since given block could be just recompressed by taking best stats from aborted run),
- some other not serious things I may be not remembering atm.

As Zopfli has built-in CRC32, local best stats database for given CRC32 and block size could be implemented (reading, appending, saving such database file) to compress given data parts in seconds instead of running through iteration process. Of course CRC32 may be not a perfect candidate for matching. Such database could be then kept somewhere online so user could download it and use for fast max compression if given data checksum has best statistics candidate.

**Comment by PeterDaveHello** [comment]
Thanks for your prompt reply, if you don't mind, maybe we can try to work on the merging works, @lvandeve what do you think?

**Comment by MrKrzYch00** [comment]
Haha, I know I can't merge original changes to my fork automatically anymore due to too many changes that already occured. :)

Btw. In-memory held statistics for instant compression of blocks that were already compressed if exactly the same data pattern is detected (using crc32 for this may be not too wise, I wonder when we get collisions) - mainly to be used for --pass# (recompression switch) or to further implement some database of them in a file to speed up compression (which would require additional info stored as there are these special commands).

**Comment by MrKrzYch00** [comment]
Not really an issue. Depends on upstream devs decision.
